# Generated by Django 4.2.7 on 2023-11-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='productsold',
        ),
        migrations.AddField(
            model_name='seller',
            name='totalproductsold',
            field=models.IntegerField(default=0),
        ),
    ]
